name: infolab
services:
# ---
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - ENV POSTGRES_DB=${POSTGRES_DB:-infolab}
      - ENV POSTGRES_USER=${POSTGRES_USER:-infolab}
      - ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-infolab}
    command: ["npm", "run", "dev"]
    ports:
      - '3000:3000'
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app
          target: /infolab/app
        - action: rebuild
          path: package.json
    networks:
      - infolab
# ---
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-infolab}
      POSTGRES_USER: ${POSTGRES_USER:-infolab}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-infolab}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - infolab
# ---
volumes:
  postgres:
# ---
networks:
  infolab:
