name: infolab
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.node
      target: production
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - infolab

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - infolab

volumes:
  postgres:

networks:
  infolab:
