name: "Epic"
description: "A template for capturing epics with high-level requirements and objectives."
labels: "Epic"
projects: "infolab"
body:
  - type: markdown
    attributes:
      value: |
        Use this template to define epics clearly. Fill in all sections to ensure we capture the necessary information for development.

  - type: input
    id: epic_title
    attributes:
      label: Epic title
      description: "Provide a concise title for the epic."
      placeholder: "Epic title goes here"
    validations:
      required: true

  - type: textarea
    id: epic_description
    attributes:
      label: Epic description
      description: "Provide a detailed description of the epic, its purpose, and high-level requirements."
      placeholder: "Describe the goal and purpose of the epic"
    validations:
      required: true
