name: User Story
description: A template for capturing user stories with detailed requirements and specifications.
body:
  - type: markdown
    attributes:
      value: |
        Use this template to define user stories clearly. Fill in all sections to ensure we capture the necessary information for development.

  - type: input
    id: story_title
    attributes:
      label: User Story Title
      description: "Provide a concise title for the user story."
      placeholder: "As a user, I want to..."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Explain the user story in detail."
      placeholder: "Add the user story description here."
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups
      description: "Link to any relevant mockups or designs."
      placeholder: "Paste links to mockups here."
    validations:
      required: true
    
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: "List the criteria that need to be met for the story to be considered complete."
      placeholder: "1. \n2. \n3."
    validations:
      required: true

  - type: textarea
    id: prerequisites
    attributes:
      label: Prerequisites (and Dependencies)
      description: "List any prerequisites or dependencies for this user story."
      placeholder: "Any prior tasks or dependencies."
    validations:
      required: true
    
  - type: textarea
    id: useful_technical_info
    attributes:
      label: Useful Technical Information
      description: "Include any technical details that may assist in implementation."
      placeholder: "Technical information goes here."
    validations:
      required: true

  - type: textarea
    id: technical_task_list
    attributes:
      label: Technical Task List
      description: "List any specific technical tasks related to this user story."
      placeholder: "1. \n2. \n3."
    validations:
      required: true
    
  - type: checkboxes
    id: additional_notes
    attributes:
      label: Additional Notes
      description: "Select any relevant notes or considerations."
      options:
        - label: "This user story impacts other functionalities."
        - label: "This story needs design review."
        - label: "Test cases need to be written."
