name: Build and Push Docker Images to GitHub Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Node image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.node
          push: true
          tags: ghcr.io/${{ github.repository }}/node:latest

      - name: Build and push Postgres image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.postgres
          push: true
          tags: ghcr.io/${{ github.repository }}/postgres:latest

      - name: Verify the images were pushed
        run: |
          echo "Node image has been pushed to GitHub Container Registry: ghcr.io/${{ github.repository }}/node:latest"
          echo "Postgres image has been pushed to GitHub Container Registry: ghcr.io/${{ github.repository }}/postgres:latest"
