name: Run Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: infolab
          POSTGRES_USER: infolab
          POSTGRES_PASSWORD: infolab
        options: --health-cmd="pg_isready -U infolab" --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d 

      - name: Install dependencies
        run: |
          docker-compose exec nodejs npm install  

      - name: Run tests
        run: |
          docker-compose exec nodejs npm test  

      - name: Shut down Docker containers
        run: docker-compose down  